# Generated by Django 5.0.3 on 2024-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_birthday_user_currency_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="superhost",
            field=models.BooleanField(default=False),
        ),
    ]
